### ISSUE TITLE
cshark openwrt compilation error

### ISSUE THREAD

**Issue by danielpetre** [cloudshark/cshark#2]
Hello.
Can this be fixed ? Thanks!

https://dev.openwrt.org/ticket/19147

"Scanning dependencies of target cshark
make[6]: Leaving directory `/home/development/src/openwrt-trunk/openwrt/build_dir/target-i386_i486_uClibc-0.9.33.2/cshark-2014-07-02'
make[6]: Entering directory `/home/development/src/openwrt-trunk/openwrt/build_dir/target-i386_i486_uClibc-0.9.33.2/cshark-2014-07-02'
[ 25%] Building C object CMakeFiles/cshark.dir/src/cshark.c.o
[ 50%] Building C object CMakeFiles/cshark.dir/src/pcap.c.o
[ 75%] Building C object CMakeFiles/cshark.dir/src/uclient.c.o
/home/development/src/openwrt-trunk/openwrt/build_dir/target-i386_i486_uClibc-0.9.33.2/cshark-2014-07-02/src/uclient.c:35:23: fatal error: json/json.h: No such file or directory
 #include <json/json.h>
                       ^
compilation terminated.
make[6]: *** [CMakeFiles/cshark.dir/src/uclient.c.o] Error 1"

**Comment by lperkov** [comment]
Thank you for the report. I've updated the OpenWrt package and it should work again now. This was due to json -> json-c switch that we had recently in trunk.
